clib/diff_tensor.so: clib/diff_tensor.c
	gcc -llapack -o clib/diff_tensor.so -shared -fPIC clib/diff_tensor.c

test:
	python3 tests/test_bead.py
	python3 tests/test_box.py
	python3 tests/test_diffusion.py

init:
	pip3 install -r requirements.txt

.PHONY: init test